### ISSUE TITLE
Authority header is never passed from client

### ISSUE THREAD

**Issue by rosecoder** [grpc/grpc-swift-nio-transport#29]
The `:authority`-header is never passed. This is an issue where all calls to APIs and services in Google Cloud Platform will fail due to their backend can not route the request resulting in a drop of request (with a `RST_STREAM`).

Looking at the headers passed, the `:authority`-header is missing:
https://github.com/grpc/grpc-swift-nio-transport/blob/565aae3d57c227a40389862dd4923da09c9ed452/Sources/GRPCNIOTransportCore/GRPCStreamStateMachine.swift#L639-L648

According to the documentation linked in the code, it's required by gRPC: https://github.com/grpc/grpc/blob/7f664c69b2a636386fbf95c16bc78c559734ce0f/doc/PROTOCOL-HTTP2.md#requests

Currently no workaround for this from a library consumer perspective due to pseudo headers must come first.

**Comment by rosecoder** [comment]
I did a quick fix for this: https://github.com/grpc/grpc-swift-nio-transport/compare/main...rosecoder:grpc-swift-nio-transport:authority-header?expand=1

It's not optimal solution, but let me know if I should open a PR.

**Comment by glbrntt** [comment]
Thanks for filing this issue @rosecoder – this had been on my mind to fix. I think the solution we'd want would be slightly wider than your fix. For example we'd want to be able to derive the authority and to override it on a per-channel basis, and it should also be used to set the TLS server hostname.

**Comment by rosecoder** [comment]
I totally agree with you on a wider fix is better + it should also populate the TLS server hostname. Using my quick fick in the mean time 👍

**Comment by rosecoder** [comment]
Noticed the [1.0.0-beta1](https://github.com/grpc/grpc-swift-nio-transport/releases/tag/1.0.0-beta.1)-release with a real fix for this issue.

Tested and confirmed that it works 👍. Closing this issue.
