### ISSUE TITLE
”Channel isn't ready.” after client being ideal for a while

### ISSUE THREAD

**Issue by rosecoder** [grpc/grpc-swift-nio-transport#40]
I see the following error message: ”14 UNAVAILABLE: Channel isn't ready.”. This happens for all client request after the process has been ideal for a while (sometimes < 5 minutes). Once this happens all requests fails. Restarting the process temporarily solves the issue.

I can reproduce this booth locally on macOS and when running containerized (Linux) in the cloud.

Let me know if this is a known issue already; if not, let me know if more details on how to reproduce this is needed.

Tested on [1.0.0-beta.1](https://github.com/grpc/grpc-swift-nio-transport/releases/tag/1.0.0-beta.1)-release.

**Comment by glbrntt** [comment]
Thanks @rosecoder – I see the problem, after the client becomes idle it enqueues new requests without ever telling the channel to reconnect. 

The idle time is configurable, you should be able to set it to `nil` on the client transport as a workaround:

```swift
        transport: .http2NIOPosix(
          target: .ipv4(host: host, port: port),
          transportSecurity: .plaintext,
          config: .defaults {
            // disable the connection idle
            $0.connection.maxIdleTime = nil
          }
        )

```

**Comment by rosecoder** [comment]
Hi @glbrntt! I would like to re-open this issue. Still seeing the same issue.

Tested on the ref for the PR above: [cad03dbd3020b7d5311becd7bc54113172337dbf](https://github.com/grpc/grpc-swift-nio-transport/commit/cad03dbd3020b7d5311becd7bc54113172337dbf).

Also getting the same issue with `maxIdleTime` set to `nil` as you mentioned above.

Here's a somewhat minimal code to reproduce this issue. Note the delay is currently set to 6 minutes.

```swift
import GRPCCore
import GRPCNIOTransportHTTP2
import GoogleCloudTracing // only used for the client type

// Setup client
let grpcClient = GRPCClient(transport: try .http2NIOPosix(
    target: .dns(host: "cloudtrace.googleapis.com"),
    transportSecurity: .tls
))
let client = Google_Devtools_Cloudtrace_V2_TraceService.Client(wrapping: grpcClient)

// Function for calling the client
func doCall() async {
    do {
        _ = try await client.batchWriteSpans(.init())
    } catch {
        print("Error: \(error)")
    }
}

// Start client
let clientTask = Task {
    try await grpcClient.run()
}

// First call
await doCall() // this one is successful

// Wait for some time
try await Task.sleep(for: .seconds(60 * 6))

// Second call
await doCall() // here it logs: Error: unavailable: "Channel isn't ready."

// Shutdown
grpcClient.beginGracefulShutdown()
try await clientTask.value
```

Let me know if there's anything else I can support with on this issue.

**Comment by glbrntt** [comment]
Sorry about that @rosecoder – clearly there was more than one problem! I'll look into this 👀

**Comment by glbrntt** [comment]
@rosecoder this should be fixed now -- thanks for the repro, it helped a lot and I verified the fix against it. Please let me know if you run into any more issues!

**Comment by rosecoder** [comment]
Great, I can confirm that it's working now 👍

**Comment by rosecoder** [comment]
Tested on larger scale and can see some `unavailable: "Channel isn't ready."` still. Can't reproduce, but here's what I'm seeing in some logs:

1. RPC 1 is successful
3. RPC 2 fails with said error
4. *10 ms later*
5. RPC 2 tried again, but fails with said error
6. *~100 ms later*
7. RPC 3 is successful

I'll let you know if I can find any more details on this.

**Comment by glbrntt** [comment]
Did you find any more info on this @rosecoder? 

My hunch is that between RPC 1 and 2 the channel enters the transient failure state and that RPC 2 is failing because of that. The default behaviour is to immediately fail all RPCs when the channel is in that state, you can change that behaviour via by setting `waitForReady` to `true` either on the `CallOptions` or via `ServiceConfig`.
